name: Test

on:
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
          always-auth: true
          registry-url: 'https://npm.pkg.github.com/'
      - run: |
          yarn install --frozen-lockfile
          yarn format:check
          yarn tsc
          yarn build
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
